DROP TABLE IF EXISTS TIPO_MONEDA;
DROP TABLE IF EXISTS TIPO_CAMBIO;

CREATE TABLE TIPO_MONEDA (
	NID_TIPO_MONEDA BIGINT AUTO_INCREMENT PRIMARY KEY,
	FLG_STATUS INTEGER NOT NULL,
	TXT_ISO_DIVISA CHAR(3) NOT NULL,
	TXT_DESCRIPCION VARCHAR(255) NOT NULL

);

CREATE TABLE TIPO_CAMBIO (
	NID_TIPO_CAMBIO BIGINT AUTO_INCREMENT PRIMARY KEY,
	FLG_STATUS INTEGER NOT NULL,
	TXT_ISO_DIVISA_BASE CHAR(3) NOT NULL,
	NUM_VALOR_MONETARIO DECIMAL(19,2) NOT NULL,
	NID_TIPO_MONEDA BIGINT NOT NULL
	
);


ALTER TABLE TIPO_CAMBIO
    ADD FOREIGN KEY (NID_TIPO_MONEDA) 
    REFERENCES TIPO_MONEDA(NID_TIPO_MONEDA);
	

INSERT INTO TIPO_MONEDA (FLG_STATUS, TXT_ISO_DIVISA, TXT_DESCRIPCION) 
VALUES (1, 'PEN', 'SOL PERUANO');
INSERT INTO TIPO_MONEDA (FLG_STATUS, TXT_ISO_DIVISA, TXT_DESCRIPCION) 
VALUES (1, 'USD', 'DOLAR AMERICANO');
INSERT INTO TIPO_MONEDA (FLG_STATUS, TXT_ISO_DIVISA, TXT_DESCRIPCION) 
VALUES (1, 'EUR', 'EURO');

commit;

INSERT INTO TIPO_CAMBIO (NID_TIPO_MONEDA, TXT_ISO_DIVISA_BASE, NUM_VALOR_MONETARIO, FLG_STATUS)
VALUES (1, 'USD', 4.10, 1);
INSERT INTO TIPO_CAMBIO (NID_TIPO_MONEDA, TXT_ISO_DIVISA_BASE, NUM_VALOR_MONETARIO, FLG_STATUS)
VALUES (1, 'EUR', 4.85, 1);

INSERT INTO TIPO_CAMBIO (NID_TIPO_MONEDA, TXT_ISO_DIVISA_BASE, NUM_VALOR_MONETARIO, FLG_STATUS)
VALUES (2, 'PEN', 0.24, 1);
INSERT INTO TIPO_CAMBIO (NID_TIPO_MONEDA, TXT_ISO_DIVISA_BASE, NUM_VALOR_MONETARIO, FLG_STATUS)
VALUES (2, 'EUR', 1.18, 1);

INSERT INTO TIPO_CAMBIO (NID_TIPO_MONEDA, TXT_ISO_DIVISA_BASE, NUM_VALOR_MONETARIO, FLG_STATUS)
VALUES (3, 'PEN', 0.21, 1);
INSERT INTO TIPO_CAMBIO (NID_TIPO_MONEDA, TXT_ISO_DIVISA_BASE, NUM_VALOR_MONETARIO, FLG_STATUS)
VALUES (3, 'USD', 0.85, 1);

commit;










